v1.14.3 Bring bijection dependency inline with scalding (#99)
Partially reverses work-around introduced in
https://github.com/CommBank/uniform/commit/9e42859738e39176c089871e0cadc12629c18238

Previous version of bijection (0.7.2) is not compatible with current
version of scalding-parquet (0.16.0). Incompatibility manifests itself
at runtime as a NoSuchMethodError when using
com.twitter.scalding.parquet.tuple.TypedParquet.

Note that the in-house packaged version of bijection is no longer
needed, as bijection-scrooge for scala 2.11 is now
available.

Also minor non-functional formatting alignment fix.